### ISSUE TITLE
Tweets should reply to the previous tweet, not the original tweet

### ISSUE THREAD

**Issue by jeremyfelt** [JJJ/publishiza#3]
Note: I have not actually tried the plugin yet, I have just read @jjj's tweetstorm. :)

IMO, each tweet in a tweetstorm is a reply to the last tweet in the chain. This way, when you open one tweet, you see all of the tweets above or below it.

It seems like the current output uses the initial tweet for all replies.

**Comment by markjaquith** [comment]
@jeremyfelt is correct. The way to get threading to work correctly is to reply to the previous one in the chain.

**Comment by JJJ** [comment]
Thanks @jeremyfelt & @markjaquith.

I wasn't sure what the etiquette was here, so went with what felt right without doing much research.

This is relatively easily achieved, but means each request will need to wait for the one before it. In other words, they'll all need to be blocking. They are currently, so that's fine.

I have in my imagination, improvements to the UX of waiting for tweets to go out. Likely a ThickBox style modal window with progress bars for each Tweet, and an ability to cancel if you're feeling remorseful.

**Comment by markjaquith** [comment]
@JJJ I like that UX idea. If a tweet fails, you could allow the user to resume posting at that point. Is Twitter gonna get butthurt about rapid tweet posting? If so, that UX would help for intentional delays, so the user doesn't think it just hung.

**Comment by JJJ** [comment]
@markjaquith Twitter does have rate-limits, and I do not think it will take very long to reach them if many of us start using this.

> Tweets: 2,400 per day. The daily update limit is further broken down into smaller limits for semi-hourly intervals. Retweets are counted as Tweets.

I suppose if this actually becomes a worthwhile endeavor, monetization (or generous donations) will have to happen to raise the roof.

In addition, they have (what I think are) reasonable rules in place that Publishiza does not violate, but does maybe walk a fine line.

<img width="698" alt="screen shot 2016-12-16 at 1 57 39 pm" src="https://cloud.githubusercontent.com/assets/88951/21276606/cc9284c4-c397-11e6-9a26-fd2f467055d3.png">

"The Twitter Rules" page largely includes code-of-conduct type stuff; nothing about rate limits.

**Comment by JJJ** [comment]
> that UX would help for intentional delays, so the user doesn't think it just hung.

That's my thought also. Right now it just `sleep( 2 )`'s between tweets, which again was a totally arbitrary guess. I've considered humanizing the delay based on the number of words, but since (right now) it blocks PHP for each tweet, I didn't want to risk timeouts with lengthy delays between many remote requests.
