### ISSUE TITLE
enhancement idea 

### ISSUE THREAD

**Issue by modemlooper** [JJJ/publishiza#7]
Neat idea but the UX could be better. If needs to be much faster to create. WP posting is too slow for a "storm". If I built this I'd use CMB repeatable field. Create the whole thing and then publish. Send each field as a tweet then compile the all the fields into a nice post.

**Comment by JJJ** [comment]
Hey @modemlooper. Thanks for the suggestion.

My initial feel is that it sounds more complex, but I may be misunderstanding.

The premise is to make this as simple and automatic as possible – not to curate individual tweets to storm, but to write a blog post as per normal – letting Publishiza process the original thoughts into a format that happens to be more appropriate for Twitter.

The same could happen for other platforms, too, but tweet-storms... so hot right now. 🔥

From the comments in #3, the UX improvements I had in mind were for after the 'push-publish' click, to provide some semblance of progress to the author to say "this is happening because you wanted it to, and here is where we are in the process."

Do you think that's an OK next step to take, and see if that satisfies your desire for the something-more-than-nothing we have currently?

**Comment by modemlooper** [comment]
Maybe I'm confused. I don't see a way to create a series of tweets that are replies.  Just a blog post that turns button to post it as a tweet.

**Comment by JJJ** [comment]
> I don't see a way to create a series of tweets that are replies.

The `post_content` is broken up into however many 119 character parts, and each of those is tweeted to the tweet before it, creating the thread of replies. Does that make sense?

**Comment by modemlooper** [comment]
I see. I guess I'll fork and fix. 😜

**Comment by JJJ** [comment]
Viva la GPL! 🍽🍾

**Comment by JJJ** [comment]
Closing for now. Feel free to discuss, branch, fork, reopen, whatever as needed.
